trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop
  drafts: false

variables:
  projects: '**/**/*.sln'

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'DotNet Install'
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Build'
  inputs:
    command: 'build'
    projects: $(projects)
    arguments: '--output $(Build.ArtifactStagingDirectory)/drop $(styleCopEnabled)'
- task: DotNetCoreCLI@2
  displayName: 'Dotnet Test'
  inputs:
    command: 'test'
    projects: $(testsProjects)
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/drop'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  artifact: drop
- task: PublishBuildArtifacts@1
  displayName: 'Dotnet Drop Artifacts'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Drop'
    publishLocation: 'Container'
